### ISSUE TITLE
Bandwidth optimization

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#101]
Several possibilities:
- enable setting the update_rate per entity. This would be a `Timer` on the `Replicate` component that would indicate if we should even consider this entity for replication.
  - enable overriding the update_rate for specific components of the entity (PerComponentReplicationMetadata)
  - how to reconcile the update_rate of an entity with the update_rate of the server? Should we just ignore the update_rate of the server? On the extreme, the user can set `server_send_interval` to 0 and control everything via entity send intervals
  
- once we have decided which updates we want to send:
  - have a Priority for each ReplicationGroup
  - it can be overriden at any time by the user
  - sort all replication-groups by Priority * time_since_last_update (latest_tick).
  - put all the updates in the channel, up to the cap? how do we know if we reach the cap, since we haven't serialized the messages at this point?
  - how to take into account the other channels during priority?
  
- idea:
  - when we buffer a message we need to specify a priority
  - default priority is 1.0 for messages, for replication it depends on the Replication component
  - there is a default priority per channel as well. Final message priority is message_priority * channel_priority
  - message_manager does priority accumulation when trying to add messages to packets. It knows the amount of bytes that it can use.
  - when considering which messages to add in the packet, the message_manager checks priority * time_since_buffered ( or can just add the priority score every send tick, same thing).
  - Ping channel has infinite priority?
  - because of priority we might have more updates for the same replication-group being sent at the same time. I.e. we might have updates for tick 10 and 15 for the same entity group in the buffer. In that case should we just skip sending the update for tick 10? How would we do it?

- send bandwidth is measured via the diagnostics? (since it has smoothed average, etc.)
  
CURRENT STATUS:
- added a PriorityManager on the packet sending step.
- when all channels prepare a list of packets to send, it sorts them by priority, then checks via the rate-limiter if we can send them
- how to compute priority?
  - should we accumulate priority every time we try to send?

- if can, great!
- if we can't:
  - should we just drop the message? 
    - for unreliable messages: it was unimportant anyway, so it's ok to be dropped. 
    - For reliable messages: we will retry sending it later (but we need to retry again with higher priority! so maybe on each send-retry of reliable channels we accumulate the priority?)
    - for unreliable updates: we can afford to drop it, but the priority must be accumulated for that entity if no update was sent -> need a way for the priority-accumulator or the message manager to indicate to the replication-group that the priority should change (i.e. that the message has been sent or not)
      - HOW?
        - one idea: we always generate a message id for each message buffered. If the message is a replication message, we the sender will always know the message id containing the update for the ReplicationGroup. We have a special function `buffer_replication_send` where we `buffer_send` the message (EntityAction or EntityUpdate), but also keeps track of which messages are for a replication group. When the message is actually set (i.e. not buffered with priority manager), we send a notification via a channel to the ReplicationSender that the message has been sent; in which case we can set the priority for that replication group to 0 (or to the base value). For each one where we don't get an update that it was sent, we increase the accumulated priority.
    - for reliable actions: we will retry sending it later (so the priority accumulation is done inside the reliable sender?)
    

QUESTIONS:

- I don't really like how the priority accumulation is done differently for EntityActions and reliable messages. The priority doesn't accumulate at the same rate. A solution would be to store the time or tick at which we wanted to send the message. Then we could multiply the priority by the time since we managed to send a message for the entity.
Or in practice, just have a higher priority for reliable channels?
  - SOLVED: the priority is accumulated at the same right. Every time we run the SystemSet::Send systems

- how to balance an entity's update-rate with the global update-rate? Should the global update-rate serve as a default for each entity's update-rate, but otherwise we can send packets every tick?
  - should each channel also have their own update-rate then?
  
- this could break the interpolation logic, since some entities will get updates way less frequently than how the interpolation time is progressing, no?

TODO:
- I don't like how we keep sending Updates until we receive the ack. That means we send way more packages than required. We should send an update if the component changes OR if the change_bevy_tick > last_update_ack, and it's been a sufficient time between them. (1.5 RTT?)

- When we exceed the bandwidth, nothing gets replicated anymore. why?

**Comment by Nul-led** [comment]
other possibilities for bandwidth optimization that come to mind:
- excluding unnecessary fields from replication (would either be unavailable or defaulted at the receiver end)
- updating component fields with change detection instead of the whole component
- no need to send component creation data when data matches defaults

**Comment by cBournhonesque** [comment]
The main body of work (adding the bandwidth rate limiter and the priority accumulation system) has been merged with https://github.com/cBournhonesque/lightyear/pull/106

Let's create other tickets for other ideas
