### ISSUE TITLE
Add a `send_message_to_room` helper method

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#119]
So that users can send messages to all clients that are present in a room.

The implementation is probably just:
- get the list of clients in the room
- call `send_message_to_target(M, NetworkTarget::Only(clients))`

EDIT: actually this is harder than expected because the client has no concept of rooms, only the server knows about the rooms.

**Comment by Nul-led** [comment]
broadcast sounds nicer i think

**Comment by mikeder** [comment]
Is the idea that clients can broadcast directly to other clients? If so, what is the use case? Shouldn't the server have a say in everything that gets rebroadcasted to other clients, to have a chance at sanitation or stopping toxic chat for example?

**Comment by cBournhonesque** [comment]
Yes maybe this feature is not needed; in general I find it helpful to have methods on the client to broadcast a message to other clients. It's basically just a helper; you could just have a message from client 1 to the server that includes the intended target, and then broadcast the message from the server to the other clients yourself. But in practice that is tedious to do so I think those functions can be helpful. 
If they are not useful for your use case you can simply ignore them to avoid spam/etc. issues.

Maybe the implementation can simply be "send message to all players in the same room"; the server can then figure out the list of clients that are in the same room as the original sender client and route the messages accordingly.

**Comment by cBournhonesque** [comment]
Added the method on the server-side, I'm not sure that it's useful on the client-side
