### ISSUE TITLE
feat: Implement a way to close transports at will

### ISSUE THREAD

**Issue by Nul-led** [cBournhonesque/lightyear#121]

**Comment by cBournhonesque** [comment]
To clarify, this is so that the server can disconnect a client

**Comment by cBournhonesque** [comment]
I added functions for server to disconnect a client, and client to disconnect a server.
We might want to do more things like:
- server stop listening on a specific `ServerConnection` (i.e. close a specific `ServerConnection` and disconnect all users that were on that one)
- close the connection but not the io?

But I think we can create new issues for those, the basic functionality has been implemented.
