### ISSUE TITLE
Bandwidth reduction: delta-compression and sub-component updates

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#127]
- excluding unnecessary fields from replication (would either be unavailable or defaulted at the receiver end)

-> this is already available, it is possible via the Replicate component to specify a component that won't be replicated.
I guess it's also possible to exclude fields from a component by just not serializing it.

- updating component fields with change detection instead of the whole component

- no need to send component creation data when data matches defaults (not worth it for fields since it would require at least one bit to indicate defaults being used)

- delta-compression in general

**Comment by Nul-led** [comment]
for compression maybe add a generalized trait so the user can add their own compression?

**Comment by cBournhonesque** [comment]
I'm running into a bunch of problems with type-erasure.

- If we don't type-erase: we need to make a bunch of new functions that are copy of the old ones, but have the `<C: Component + Diffable>` bound.
- If we type erase:
  - I need to clone the data from &C into an owned C that I store in the sender (so that we can compute diffs against it later).
  - I need to type-erase `diff(&self, other: &Self) -> Delta`
  - I need to type-erase `apply_delta(&mut self, delta: Delta)`
