### ISSUE TITLE
Update vendored bitcode to fix docs.rs build

### ISSUE THREAD

**Issue by tbillington** [cBournhonesque/lightyear#163]
Issue is described in https://github.com/SoftbearStudios/bitcode/issues/17.

> `bitcode` no longer compiles on the latest nightlies because it depends on `bitintr` which uses the (now removed) `stdsimd` feature.

> We removed `bitintr` in `bitcode@0.5.1`

Updating the vendored `bitcode` crate would resolve the docs.rs build issue https://docs.rs/crate/lightyear/0.10.0/builds/1134153.

**Comment by cBournhonesque** [comment]
Thanks for noticing this!
I upgraded the vendored bitcode crate and the issues now seems fixed :) 
(https://github.com/cBournhonesque/lightyear/pull/162)
