### ISSUE TITLE
Be able to update the config at runtime before the plugin actually 'starts'

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#183]
Here is an example:
- there is a lobby stage where users can select (via buttons) if they want to be 'host' or to join another client's game
- we would therefore like to be able to select the network config at runtime

Options:
- have a plugin.start() command that actually sets the params/config in stone, before that the config can be changed freely.
- or be even more flexible and have multiple `Stages`: Connected and Disconnected. (or `Prepare` and `Running`, etc.)
When the stage is `Disconnected`, the user can update the config at will, and it will take effect upon the next connection

cc @zwazel

**Comment by msvbg** [comment]
Note that it is typically also possible for players to switch who is the host at runtime, and to host multiple matches consecutively. Player A is the host during the first match, and during the second match Player B is the host and Player A is merely a client. The `plugin.start()` solution described in this issue sounds more like you can decide only _once_ which player is the host. Or am I misunderstanding?

**Comment by cBournhonesque** [comment]
So the current situation is:
- the user passes in `Config`
- the `Config` gets stored as a `Resource`, and parts of the `Config` are cloned to create a bunch of sub-plugins. (For example the `ReplicationPlugin` uses the `tick_duration`, etc.
- then the user calls `app.run()` and everything is set in stone

We could instead do something like this:
- the user passes in `Config`, it gets stored as a `Resource`.
- each subpart of the config is stored as its own `Resource`
- The user can update the `Config` via a simple `ResMut<Config>` (maybe only if the state is `Disconnected`)
  - maybe only a subset of the Config is modifiable (for example not crucial stuff like tick_duration)
- All the various subplugins aren't initialized via clone of the config, instead they just call `Res<Config>` to get the config value? so that whenever there is a change, they pick it up?

This looks like it could work; not sure about the performance of all systems reading from `Res<Config>` though.

**Comment by msvbg** [comment]
Yeah, change detection on the connection resources sounds pretty reasonable. I guess for a typical listen-server game, every player would start the game with both a server and a client plugin and if you're only running as a client, the server plugin is just dormant?
