### ISSUE TITLE
How to spawn players with sprites across clients?

### ISSUE THREAD

**Issue by MTRNord** [cBournhonesque/lightyear#220]
Hi, I am lost I think. I used https://github.com/cBournhonesque/lightyear/tree/main/examples/client_replication as a basis for my code and got the `draw_elements` working. However, instead of a rectangle, I would like to use a `SpriteSheetBundle` for the character. Doing that on the source client is quickly done by just modifying `spawn_player` in the client code.  I didn't however figure out how to do it then on the other side. Modifying the `player_id` check in `spawn_player` leads me to having an endless loop of players being spawned on both sides. Modifying `draw_elements` does spawn a new sprite bundle on each tick.

What am I missing? I feel blind tbh.

**Comment by cBournhonesque** [comment]
Do you have some code I can look at?
In general, you would listen on a component getting replicated, for example `ComponentInsertEvent<PlayerId>`, and then add render-related components when you receive that event

**Comment by MTRNord** [comment]
Hi so I tried what you said now and it kinda works but not quite and I am likely now actually mostly stuck at bevy stuff rather than lightyear stuff :)

The tile and rectangle spawning is now at https://github.com/MTRNord/placeholder_project/blob/main/src/networking/mod.rs#L68-L114
And the player bundle is spawned at https://github.com/MTRNord/placeholder_project/blob/main/src/networking/client.rs#L180-L205

The thing I now get is that if I spawn https://github.com/MTRNord/placeholder_project/blob/main/src/networking/mod.rs#L89-L98 without the parent it is stuck at 0,0 location and with parent it's not drawn due to complaining about missing global transform and visibility aka https://bevyengine.org/learn/errors/b0004/ 

I assume my code would be fine if I had the bundle entity rather than the PlayerId component entity here but the event handler only gives me the component entity. So I guess thats more of what I am confused about here.

**Comment by cBournhonesque** [comment]
Ah I see; so you probably want to run `spawn_tiles` only on the client, because it seems to contain purely render-related components (animations, textures).
I would just spawn with children directly in your `spawn_player` method.
And yes, I think it might be failing because your `PlayerBundle` is missing the `Visibility` and `Transform` components.

By the way there are 2 modes of spawning player-controlled entities:
1) just spawn the PlayerBundle on the server (when the 'Space' input is received) with the Replicate component, it will then get replicated to the client. You can listen for `EventReader<ComponentInsertEvent<PlayerId>>` on the client to know when the `PlayerId` component got replicated, then you can add additional components, etc.

2) (what you're doing, which is a bit more complicated). Spawn the PlayerBundle + children (animation, textures) directly on the client and use Pre-Prediction to transfer authority to the server. It seems to work well for your usecase though, because you can just directly spawn everything you need on the client.

**Comment by MTRNord** [comment]
So moving it as you said to the spawn_player made sense to me as well and I tried that before but with 2 clients it leads to only rendering the tiles for the local player rather than both:

![image](https://github.com/cBournhonesque/lightyear/assets/1374914/92c76a0a-7964-47da-b5a5-b1ff1f107de0)

Which I assume is caused by this piece of code which was in the examples as well:

```
for player_id in players.iter() {
        if player_id.0 == client_id {
            return;
        }
    }
```

I guess it finds the own player first and then stops. I tried to use continue and loop over all instead but that instead runs into an endless loop where there will be endless amounts of spawned entities instead.

The second option from your 2 options currently is likely better since I dont have any start menu or interaction yet (still doing the groundworks first)

**Comment by cBournhonesque** [comment]
Ah I see, that makes sense. The client code is only running for the local client.

What you should do instead is:
- when a client presses 'Space', spawn a player bundle on the server (or on the client with pre-prediction)
- on the client, listen for `ComponentInsertEvent<PlayerId>`, which means that a player got replicated
  - when that happens, spawn any extra client-side things that you need (textures, sprites, etc.)
  
This way, a client will spawn sprites for every replicated client (which is all other clients)

**Comment by MTRNord** [comment]
hm, ok that makes sense but do I still need to track the client/player id on the client? 

I can't seem to get the `PlayerId` on the client when using `mut new_players: EventReader<ComponentInsertEvent<PlayerId>>` and it's read method. On the server it's in the context, but on the client there is just `&()` in it and the entity of the already spawned `PlayerId` component. I also tried to get the `PlayerId`  from the entity but failed to get the reflection to work. I got it working with world but can't spawn things then as `ResMut` and World differ in mutability, preventing the usage of the world or the `ResMut` in the same handler.

**Comment by cBournhonesque** [comment]
You should be able to just get it from the Entity, what do you mean by Reflect?
```
fn player_spawn(
   mut commands: Commands,
   mut events: EventReader<ComponentInsertEvent<PlayerId>>,
   players: Query<(&PlayerId)>
) {
  // we received from a server the event that a new player got spawned
  for event in events.read() {
    let player_entity = event.entity();
    let player_id = players.get(player_entity).unwrap();
    // spawn extra sprites, etc.
    // commands.spawn(...)
  }
 }
 ```
 
 Something like this should work
