### ISSUE TITLE
Disconnecting the transport in wasm somehow freezes the app

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#259]
It seems to be because we don't close the two recv/send tasks here: https://github.com/cBournhonesque/lightyear/blob/698c09f8fa1159416601ea9f2c895e6d1f8a1926/lightyear/src/transport/webtransport/client_wasm.rs#L110-L110

upon disconnection; so one of the tasks panics.

**Comment by simbleau** [comment]
Thank you @cBournhonesque !
