### ISSUE TITLE
Confusion over `Netcode` authentication / `client_id`

### ISSUE THREAD

**Issue by philpax** [cBournhonesque/lightyear#307]
Hi there!

I'm experimentally integrating Lightyear into my project, and making good progress, but I'm confused as to how to specify the parameters for `client::NetConfig::Netcode::auth`. I'd like to connect to a server with a given protocol version, so I'm using `client::Authentication::Manual`, but I'm not sure about two things:

- the `client_id` is client-provided, which seems non-ideal if you have arbitrary clients connecting to a server. How do you know whether your `client_id` is already in use?
- I'm not sure if the `private_key` is meant to be the same as the one on the server. 
  
  I assume it is, but when digging into this, I noticed that there is both a `client_to_server_key` and `server_to_client_key` inside `ConnectTokenPrivate`, and I *had* to specify the same key on the server (i.e. I couldn't let it generate its own key) in order to be able to connect. 
  
  I'm fine with whatever; I just don't understand how it's meant to be used currently, and have used a zero key on both ends.

My main point of confusion is `client_id`; how do I ensure my two clients have different client IDs without pre-knowledge? Do I use a random client ID?

**Comment by cBournhonesque** [comment]
Hi,

1) Netcode is a standard for establishing connections using a ConnectToken (https://github.com/mas-bandwidth/netcode/blob/main/STANDARD.md#architecture).
In the standard, this is how things are supposed to work:
- you have one or more game servers that will run your actual game
- you have some backend server (for example a webserver) that clients connect to. 

The game server and backend server must shared the same PROTOCOL_ID and PRIVATE_KEY.

When the client connects to the backend server, the backend server **generates a ConnectToken** and sends it to the client. To generate the `ConnectToken`, the backend server will have to assign a `ClientId` to the client. It can do so in any way it prefers (maybe by looking up the user's info in an internal db, or generating a random ClientId and checking for duplicates among the existing ClientIds, etc.). The client then uses the `ConnectToken` to connect to the game server, and will only be aware of their ClientId if they are successfully connected.

The `Authentication::Manual` is provided for convenience during testing, but yes in a production setting the gameserver would be the one assigning `ClientId`s.

2) As mentioned above, the PRIVATE_KEY should be shared between the backend server and the game servers. The client should never be aware of the PRIVATE_KEY.
When testing with `Authentication::Manual`, the client is generating its own `ConnectToken`, and the private_key used must be the same as the one used in the server.

Hopefully that clears things up!
I'm working on building an example with an actual backend webserver that generates the `ConnectToken`.

**Comment by philpax** [comment]
Aha! Thank you, that's very useful. It might be worth adding documentation to the relevant pages, or adding a page to the book; I wasn't really sure how the tokens came together. The book mentions using `Manual` for the purpose of demonstration, but doesn't clarify the alternatives; I tried using `RequestToken` but you can't specify a server to connect to 😅 

Okay, so I need to generate the token on a server and push it down to the client, which will then send it to the game server. The client doesn't need to know of the private key, and this is only necessary for the `Manual` auth path as the code is forging its own token, which the backend server would normally do.

At present, I only have the one game server, and don't intend on having any backend services. What would be the best way to make this work? Should I add a HTTP server to my server so that the client can use that to retrieve a token, and then use Lightyear for the rest of the way?

**Comment by cBournhonesque** [comment]
I will update the docs to make it clearer :)

`Authentication::RequestConnectToken` is to be able to build a `ClientConfig` without actually having the token yet.
So you might have some system in your bevy app requesting a `ConnecToken`, and as soon as you have it you update the `Authentication` method. It's rather confusing right now, sorry


> At present, I only have the one game server, and don't intend on having any backend services. What would be the best way to make this work? Should I add a HTTP server to my server so that the client can use that to retrieve a token, and then use Lightyear for the rest of the way?

Yes, I think something like that would work right now.
Open some TCP port on the server which is dedicated to sending `ConnectToken`s to client who request them.
I might want to provide a way to do that in `lightyear` directly

**Comment by philpax** [comment]
Sorry for the delay in response, I ate dinner and then implemented this. 

Yep, it all seems to work now - I have a TCP server that issues client tokens in response to connections, and I can extend this to allow the users to pass authentication data as required that can then be stored in the server's memory. 

This ended up being a bit lengthier than I would have liked (because authentication server in a thread is required on the server, and a state machine with a thread to process the connection on the client), but it wasn't too bad. A more integrated method would be very welcome, I think! I suspect most users will want a single server to begin with; having an easy path to integrate would make it easier to get going "correctly". 

That being said, I've skimmed over your updates to the documentation and they address many of my points of confusion. Thank you very much for the quick response, I'm unblocked now 🙏

**Comment by cBournhonesque** [comment]
I'd be interested in seeing how you implemented this, if you were willing to share!

**Comment by philpax** [comment]
Sure! My project is still closed (I want to get more done before I open it), and this code is first-pass (i.e. I haven't extended it to support passing data to the auth server), but it's pretty straightforward:

Authentication server, which is run through `let _auth_server_thread = authentication_server::thread(&settings, client_id_to_entity_id);` in the server:
```rust
pub fn thread(
    settings: &Settings,
    client_id_to_entity_id: SharedClientIdToEntityIdHashMap,
) -> std::thread::JoinHandle<()> {
    let token_port = settings
        .token_port
        .unwrap_or(shared::settings::DEFAULT_TOKEN_SERVER_PORT);

    let server_addr = SocketAddr::new(
        settings
            .server_hostname
            .parse()
            .expect("Failed to parse server hostname"),
        settings
            .port
            .unwrap_or(shared::settings::DEFAULT_SERVER_PORT),
    );

    std::thread::spawn(move || {
        let listener =
            std::net::TcpListener::bind(SocketAddr::new(Ipv4Addr::UNSPECIFIED.into(), token_port))
                .expect("Failed to bind to token server port");

        for stream in listener.incoming() {
            match stream {
                Ok(stream) => {
                    if let Err(err) = handle_incoming_connection(
                        server_addr,
                        client_id_to_entity_id.clone(),
                        stream,
                    ) {
                        log::error!("Token server failed to handle connection: {err:?}");
                    }
                }
                Err(e) => {
                    log::error!("Token server failed to accept connection: {e:?}");
                }
            }
        }
    })
}

fn handle_incoming_connection(
    server_addr: SocketAddr,
    client_id_to_entity_id: SharedClientIdToEntityIdHashMap,
    mut stream: std::net::TcpStream,
) -> anyhow::Result<()> {
    let client_id_to_entity_id = client_id_to_entity_id.lock().unwrap();
    let client_id = loop {
        let client_id = rand::random();
        if !client_id_to_entity_id.contains_key(&ClientId::Local(client_id)) {
            break client_id;
        }
    };

    let token = ConnectToken::build(
        server_addr,
        DEFAULT_PROTOCOL_ID,
        client_id,
        DEFAULT_PRIVATE_KEY,
    )
    .generate()
    .context("Failed to generate token")?;

    let serialized_token = token
        .try_into_bytes()
        .context("Failed to serialize token")?;

    stream
        .write_all(&serialized_token)
        .context("Failed to send token to client")?;

    Ok(())
}
```

Client:
```rust

#[derive(Resource)]
/// Lightyear requires us to get a `ConnectToken` from the server in an out-of-band fashion.
/// To do this, the game server runs a TCP server that will respond to any incoming requests
/// with a `ConnectToken`.
///
/// You should insert this resource with `AuthenticationRequest` pointing to that server.
/// A system will then connect to that server and request a `ConnectToken` in a thread,
/// updating to `AuthenticationRequested`. When the token is available, this resource
/// will be removed, the client config will be updated, and the formal connection will
/// begin.
pub enum ConnectionRequestState {
    Request {
        authentication_server_address: SocketAddr,
    },
    Requested {
        /// optional so that it can be consumed
        authentication_thread: Option<std::thread::JoinHandle<ConnectToken>>,
    },
}

#[derive(Resource)]
pub struct AuthenticationServerAddress(pub SocketAddr);

// System that drives the authentication and actually connects
fn handle_connection_request(
    connection_request_state: Option<ResMut<ConnectionRequestState>>,
    mut client_config: ResMut<client::ClientConfig>,
    mut commands: Commands,
) {
    let Some(mut connection_request_state) = connection_request_state else {
        return;
    };

    match connection_request_state.as_mut() {
        ConnectionRequestState::Request {
            authentication_server_address,
        } => {
            let authentication_server_address = *authentication_server_address;
            info!("Requesting connection token from {authentication_server_address}");
            *connection_request_state = ConnectionRequestState::Requested {
                authentication_thread: Some(std::thread::spawn(move || {
                    let stream = std::net::TcpStream::connect(authentication_server_address)
                        .expect("Failed to connect to authentication server");

                    let mut reader = std::io::BufReader::new(stream);
                    let mut token = vec![];
                    reader
                        .read_to_end(&mut token)
                        .expect("Failed to read token from authentication server");

                    ConnectToken::try_from_bytes(&token)
                        .expect("Failed to parse token from authentication server")
                })),
            };
        }
        ConnectionRequestState::Requested {
            authentication_thread,
        } => {
            // Check if the thread's gotten the token yet; if so, take the thread,
            // get the token, store it, connect, and delete this resource
            if !authentication_thread
                .as_ref()
                .is_some_and(|t| t.is_finished())
            {
                return;
            }

            let authentication_thread = authentication_thread.take().unwrap();

            let token = authentication_thread
                .join()
                .expect("Failed to join authentication thread");

            let client::NetConfig::Netcode { auth, .. } = &mut client_config.net else {
                panic!("Expected Netcode config");
            };

            info!("ConnectToken received, connecting");

            *auth = client::Authentication::Token(token);
            commands.remove_resource::<ConnectionRequestState>();
            commands.connect_client();
        }
    }
}
```

By the way, it's not immediately obvious that `client::ClientConfig` is a resource. Not sure what the best way to demonstrate that would be.

**Comment by cBournhonesque** [comment]
Thanks!
I haven't provided this because it might become complex to handle all possibilities (connect via websocket in web; tcp + tls in native. + the client might want to send extra data).
But it might be useful to provide a simple implementation to begin with.

I think most users just used `Authentication::Manual` up to now

**Comment by cBournhonesque** [comment]
I added an example based on your implementation @philpax

**Comment by philpax** [comment]
Glad to have helped!

**Comment by philpax** [comment]
Apologies for continuing to dredge this thread back up, but I'm looking at extending my connection handler (i.e. system that takes `connections: EventReader<ConnectEvent>`) to retrieve information that was passed in the authentication handshake through a temporary authentication session that's created upon token creation. 

That's all straightforward, but I wanted to handle the case where there is no session present by immediately disconnecting the peer that's connected; I don't see a straightforward way to do this, as there's no equivalent to `disconnect_client` on `ServerCommands`, and I can't see an easily-accessible way to do it from a quick code search. It looks like there is a method present on the `NetServer` trait, but I don't know how to get to that from the Bevy ECS. Would appreciate any guidance you can offer!
