### ISSUE TITLE
Log spam when a connection is terminated

### ISSUE THREAD

**Issue by philpax** [cBournhonesque/lightyear#322]
When one half of a connection is forcibly terminated (application shut down or crashes), the other side will spam log messages.

**Client shut down without disconnecting from the server**:
```
2024-05-08T01:18:28.548678Z ERROR lightyear::server::networking: Error updating netcode server: could not update server

Caused by:
    An existing connection was forcibly closed by the remote host. (os error 10054)
2024-05-08T01:18:28.551035Z ERROR lightyear::server::networking: Error updating netcode server: could not update server

Caused by:
    An existing connection was forcibly closed by the remote host. (os error 10054)
[repeat dozens of times]
```

**Server shut down without disconnecting its clients / the clients disconnecting**:
```
2024-05-08T01:18:29.602614Z ERROR lightyear::client::networking: Error updating netcode: could not update client    
2024-05-08T01:18:29.705763Z ERROR lightyear::connection::netcode::client: error updating client: Transport(Io(Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." }))    
2024-05-08T01:18:29.706336Z ERROR lightyear::client::networking: Error updating netcode: could not update client    
2024-05-08T01:18:29.724577Z ERROR lightyear::connection::netcode::client: error updating client: Transport(Io(Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." })) 
[repeat dozens of times]
```

I suspect this might be a Windows-exclusive issue, but I haven't tested on the other platforms yet.

---
I could alter my logging settings to hide messages from the relevant modules, but I'd like the messages in general - this one's just a bit spammy!

**Comment by Nul-led** [comment]
seems like netcode isnt made aware of the disconnect

**Comment by cBournhonesque** [comment]
> seems like netcode isnt made aware of the disconnect

Yes, when the io gets closed, the netcode protocol isn't made aware of it.
This happens in all platforms; thanks for the report!

**Comment by cBournhonesque** [comment]
Actually which transport were you using? I haven't managed to reproduce this (although I definitely saw this before)

**Comment by philpax** [comment]
Netcode, haven't used any of the other transports.

**Comment by cBournhonesque** [comment]
Webtransport / UDP / Websockets?

**Comment by philpax** [comment]
Oh sorry, UDP.

**Comment by cBournhonesque** [comment]
I think I fixed the client spam logs when the server gets suddenly disconnected with https://github.com/cBournhonesque/lightyear/pull/340
(client monitors the io, if the io disconnects it also disconnects netcode)

I wasn't able to reproduce the opposite issue (server is running and client suddenly disconnects)

**Comment by philpax** [comment]
I've just updated my code to the latest `lightyear` HEAD (`6f02f6179`) and can confirm that I'm still seeing this. To rule out an issue with my code, I've tested `simple_box` and I can confirm that I still see it on Windows 11 x86-64 over UDP:

https://github.com/cBournhonesque/lightyear/assets/707827/61f3d165-52ac-457a-bd61-88b77857dfef

The only change I've made is to switch over to UDP instead of WebTransport for the connection in `settings.ron`.

**Comment by cBournhonesque** [comment]
Thanks for the confirmation; does it also happen with WebTransport?

**Comment by philpax** [comment]
Nope, works fine with WebTransport on both ends.

**Comment by cBournhonesque** [comment]
Ok great! Thank you, I know what to fix

**Comment by cBournhonesque** [comment]
Actually this thread: https://www.reddit.com/r/rust/comments/a2hh6n/cannot_handle_os_error_while_using_udpsocket/
seems to suggest that this error happens if you try to send a message to a remote UDP socket that is closed.

However the error only manifests when you call the recv() function.
The problem is that I don't know how to identify the connection which caused this error to be emitted, as it doesn't seem to be part of the error. So I don't know which connection to close..

**Comment by philpax** [comment]
Hmm yeah, that's pretty annoying :/

Do you get an error from `send` if you try sending to the closed socket, or is it just in `recv`? That is, can you detect transmission failure once this state begins, or do the errors only appear in `recv`?

The netcode timeout should handle it eventually, but it'd be nice to avoid dead logs / the error handling logic. (Capturing backtraces with `anyhow` is *expensive*!)

**Comment by cBournhonesque** [comment]
I will have to do more testing. Hopefully i get an error in send? I think it be only in recv though.
Also this doesn't happen for me on mac, I'll try to test on windows

**Comment by philpax** [comment]
I haven't seen this happen recently, with either graceful or forced termination, so I'll close the issue for now 🙂
