### ISSUE TITLE
Be able to update the `Replicate` component at runtime

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#329]
This might be easier once we have observers, because then I could inspect both the old Replicate and the new Replicate value at the same time, to compute a diff:
- clients to which we don't network anymore: send entity despawn
- clients that were added to NetworkTarget: send entity spawn + send component insert for every relevant component
- per_component_metadata for which we don't replicate anymore: send component remove
- per_component_metadata for which we do replicate: send component insert

EDIT:
actually observers won't help with this

Periwink — Today at 2:44 PM
Observers trigger before the actual ECS update; so if I want to update a Component A on entity that as A, the observer would allow me to have access to both the old data (via a Query) and the new data (in the observer trigger)? @James 🦃

Or maybe not, if the ECS change happens first, before the observer commands are executed at the next apply_deferred 
James 🦃 — Today at 2:49 PM
No, the observers trigger after an insert and before a remove
The observers run immediately, then don't wait until apply_deferred, but any commands queued by the observer will
You can fetch the inserted component or view the removed component before it is removed but you can't see the value before it's overwritten (although you can implement that behaviour by storing a copy of the value elsewhere and look at that on the next insert)

**Comment by cBournhonesque** [comment]
Should we split up the Replicate component into a bundle of multiple components?
- `NetworkTarget`
- `Control`
- `Visibility`
- `Hierarchy`
- `Group`
- `TargetEntity`

- `PerComponentNetworkTarget<C>`
- `PerComponentReplicateOnce<C>`
(or just `PerComponentReplicateMetadata<C>`)

- it's still relatively ergonomic for the user since they can use the bundle
- allows for more modularity when fetching the data that we need
- would make things simpler when updating a single sub-set of the component

**Comment by msvbg** [comment]
Sounds good to me, I think it's generally more idiomatic to have small components rather than large ones

**Comment by Nul-led** [comment]
Could improve parallelization too
