### ISSUE TITLE
Only apply replication updates if the new value is different from the existing value

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#341]
- This could be useful to avoid triggering change detection

- might require a PartialEq bound. Or should we make PartialEq optional?

**Comment by msvbg** [comment]
This should probably use the `equality_fn`, not `PartialEq`?

**Comment by cBournhonesque** [comment]
Maybe, if we go though the optional PartialEq work

**Comment by cBournhonesque** [comment]
The problem with the optional PartialEq approach is that it would add more verbosity to the protocol:
```
app.register_component::<C>()
     .add_default_equality_fn();   // available only for types that are PartialEq
```
or 
```
app.register_component::<C>()
     .add_equality_fn(equality_fn); 
```

Also the equality function for change detection during replication might not be the same as the one used for rollback checks (the thresholds might be different).

One solution could be to require all networked type to be PartialEq

**Comment by msvbg** [comment]
Maybe requiring PartialEq is easiest for now

**Comment by philpax** [comment]
I assumed `PartialEq` was already necessary for this kind of thing, so I don't think it'd be too much of an imposition to require it now. Users who need custom behaviour can always newtype it and provide their own `PartialEq` implementation, right?
