### ISSUE TITLE
Provide a more expressive way to replicate only a subset of components of an entity

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#360]
For example what if a user only wants to replicate one component?

**Comment by Nul-led** [comment]
I cant really think of anything to implement this with a user facing api. Maybe implementing a certain trait for each component that returns a "do_replicate" bool for a given entity, but in practice this wouldnt work well either as the overhead would be huge

**Comment by Nul-led** [comment]
Another idea might be having markers / tags for each replicated (or non-replicated for that matter) component

**Comment by Nul-led** [comment]
@cBournhonesque can we close this? i think so cuz we have the exclusion marker

**Comment by cBournhonesque** [comment]
I wanted to be a handle the other case: If you only want to replicate 1 component out of 20, you have to add 19 DisableComponent<C> components, which is not ideal
