### ISSUE TITLE
`MessageEvent` isn't in the prelude - Separate preludes?

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#389]
I find it pretty weird that `MessageEvent` isn't in the prelude

Well, actually not really. There is a server::MessageEvent and a client::MessagEvent.

Do we want to split two preludes, e.g. `server::prelude` and `client::prelude`? 

Most apps are separated, anyways, I see no reason not to.

**Comment by cBournhonesque** [comment]
The prelude is already separated; there is `prelude::client::*` and `prelude::server::*` :)
