### ISSUE TITLE
Dynamic server address?

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#393]
I'm a bit stuck on how I'm supposed to connect to a server address that isn't known statically.

For example,

Client:
- Downloads a list of worlds (IP:Port)
- Chooses a world
- Connects to that world

Currently it looks like that is put in the Plugin itself, and I'm unsure of how to change the config.

**Comment by cBournhonesque** [comment]
Hi,
The docs should make this more clear, but the ClientConfig and ServerConfig are `Resources` and can be modified at will. The changes will take effect on the next time that the client connects, or that the server starts.

The lobby example shows exactly this: https://github.com/cBournhonesque/lightyear/tree/main/examples/lobby

The client connects to a dedicated server which syncs a list of lobbies, and then it can dynamically join a game (where the server could be either the dedicated server or another client which acts as host) by updating the `NetConfig`
