### ISSUE TITLE
Weird inputs when server-send-interval is too long (leafwing inputs)

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#396]
- server_send_interval = 1000ms
- server link condirtion is None
- client link conditioner  is:
            conditioner: Some(Conditioner(
                latency_ms: 75,
                jitter_ms: 10,
                packet_loss: 0.02
            )),
            
weird issue where if i tap eg Left it appears that the actionstate for left remains pressed for far too long, i think as long as the server_send_interval

the client is seeing my Left key as pressed for a whole second (~64 ticks) even tho i just tapped the key.  looks like the server only sees it pressed for 2/3 of a second or so, weirdly. still investigating

disabling diffs means the server sees the correct inputs for each tick, client still misbehaving.

**Comment by RJ** [comment]
i neglected to stop the server's actionstate replicating to the client, adding this on the server spawned player entity was needed, as the comment from the demo explains:
```rust
    // We don't want to replicate the ActionState to the original client, since they are updating it with
    // their own inputs (if you replicate it to the original client, it will be added on the Confirmed entity,
    // which will keep syncing it to the Predicted entity because the ActionState gets updated every tick)!
    OverrideTargetComponent::<ActionState<PlayerActions>>::new(
        NetworkTarget::AllExceptSingle(client_id),
    ),
```
