### ISSUE TITLE
PreSpawned object errors when doing remote-client prediction

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#408]
When sending PreSpawned objects to remote players, aka player 1 presses Fire and spawns a PreSpawned object locally, and the Fire input gets replicated to player 2 (via ActionState replication). We sent player 1 inputs to player 2 because we want to do remote player prediction.

The server also receives player 1's Fire input and spawns a bullet that will be replicated to all clients (and probably predicted on all clients).

2 cases:
- either the ActionState from player 1 is replicated before the bullet, and then player2 spawns a PreSpawned object which then gets merged into the replicated bullet (via hash matching)
- either the server bullet is replicated before the ActionState, and in this case we get 2 bullets:
  - the first bullet is replicated from the server
  - the second bullet comes from the ActionState. It survives for a bit but then is despawned because it couldn't match with a server entity (via hash matching) because the server entity was spawned before!!
  
 The solution might be to allow hash matching in both directions? ServerReplicated into PreSpawnedClient, and PreSpawnedClient into ServerReplicated?
 
 Currently the `PreSpawnedObject` component is removed immediately on the initial matching attempt.

**Comment by cBournhonesque** [comment]
Doing the matching in both directions seems pretty brittle, maybe the best solution is for users to follow the rule:

**Do not spawn pre-spawned player objects using inputs from remote players!**
This will result in double-spawning the entity (once because it's replicated from the server, and once locally when applying the remote-input.

**Comment by RJ** [comment]
I've handled this by only pre spawning bullets for remote players if I have their inputs early - ie, we are not in rollback when we see the PlayerAction Fire for the current tick.

In cases where remote player inputs arrive late, the server spawns the bullet and it gets replicated normally (triggering a rollback). 

Adding my firing system like this:
```rust
   shared_player_firing.run_if(not(is_in_rollback)),
```

safe to close this imo
