### ISSUE TITLE
Add example with physics and more chances of rollback

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#41]
- Current examples don't really have rollback unless the networking is bad, because there is no interactions with the environment so there is no possibility of the client predicting something completely wrong (for example that they kicked the ball, when in fact the second player kicked it)

- Try an example that is like a 2D rocket-league:
  - multiple players
  - a ball
  - they are all predicted by all clients

- See how this performs, and if we need to interpolate the rollback result instead of completely snapping back to the new state.
- Rewatch the rocket-league GDC video

**Comment by Nul-led** [comment]
I see potential here for showcasing integration with other crates as well. In this case something like bevy_rapier or bevy_xpbd should be preferable over a custom physics impl anyways even if its just to save time.

**Comment by cBournhonesque** [comment]
This is now supported with the addition of the [leafwing_inputs](https://github.com/cBournhonesque/lightyear/tree/main/examples/leafwing_inputs) example
