### ISSUE TITLE
`Visibility` should be renamed

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#437]
I have my own prelude for my engine, which I feel is a fairly reasonable thing to do, and in it, I re-export the bevy::prelude.

There is a `bevy::prelude::Visibility` and a `lightyear::prelude::Visibility`.

This leads to an `anonymouse_glob_exports` lint, you can easily reproduce via:

```rust
pub mod prelude {
        bevy::{
            self, ecs as bevy_ecs,
            log::{debug, error, info, warn},
            prelude::*,
            utils::{Duration, Instant, SystemTime},
        },
        lightyear::prelude::*,
        ...
}
```

**Comment by cBournhonesque** [comment]
Maybe also rename `ServerConnections`, which is type-prone
