### ISSUE TITLE
Large messages fail to deserialize / panic

### ISSUE THREAD

**Issue by Serverator** [cBournhonesque/lightyear#449]
# Problem
When sending a message that is more than 300 kilobytes in size, received message will fail to deserialize on the client and crash the server.

On the client it prints this message:
```
2024-06-04T06:51:16.980360Z ERROR lightyear::client::message: Could not deserialize message
```
On the server it crashes with this error:
```
thread 'main' panicked at lightyear\src\server\connection.rs:618:30:
Could not decode ClientMessage: Error(Eof)
Encountered a panic in exclusive system `lightyear::server::networking::receive`!
```

# Example
I made an example that will send 300 kilobytes of random data from client->server and from server->client on connection
https://github.com/Serverator/lightyear_playground/tree/large_message

- `cargo run -- server` to start the server
- `cargo run -- client` to start the client

Server and client will show problems as described above

# Might be related
I've had this error message in my log when I first tried it on commit `80f460cd`. As commit is 4 days old it might have been already fixed.
```
2024-06-04T06:27:23.865439Z  INFO lightyear::connection::netcode::client: client connected to server
thread 'main' panicked at lightyear\src\channel\receivers\fragment_receiver.rs:98:26:
index out of bounds: the len is 89 but the index is 89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in exclusive system `lightyear::client::networking::receive`!
2024-06-04T06:27:24.336545Z  INFO lightyear::transport::webtransport::client_native: WebTransport connection closed. Reason: client requested disconnection. Shutting down webtransport tasks.
```

**Comment by Nul-led** [comment]
> I'll have to check but I think it might not be possible to send messages of this size.
> The fragmentation uses a u8 to track the number of fragments, so the max is 255 fragments.
> Each fragment is roughly 1200 bytes so the max would be 255 * 1200 = 300KB.
> 
> Maybe I can change it to an u16? I would have to benchmark to see if it's worth, because it should be very rare to send messages of this size

In that case this behavior should be indicated and panic before sending 🤔

**Comment by msvbg** [comment]
> In that case this behavior should be indicated and panic before sending

I would like it if lightyear logs an error and tries to continue gracefully wherever possible.

**Comment by cBournhonesque** [comment]
> > In that case this behavior should be indicated and panic before sending
> 
> I would like it if lightyear logs an error and tries to continue gracefully wherever possible.

Good suggestion! Fixed here: https://github.com/cBournhonesque/lightyear/pull/454
