### ISSUE TITLE
client gets into weird state after idling for a while

### ISSUE THREAD

**Issue by RJ** [cBournhonesque/lightyear#482]
while testing spaceships example, if i leave a chrome wasm client connected for a while and come back later, it is in some weird state where position warps around a bit. will try and get a video and update this issue.

**Comment by Nul-led** [comment]
What do you mean by "a while"?

**Comment by RJ** [comment]
with just 1 client connected, after a while of inactivity the server spews a bunch of:
`System 'bevy_ecs::event::event_update_system<.......>' has not run for 3258167296 ticks. Changes older than 3258167295 ticks will not be detected.`
then when i try to play, something is pretty messed up with position and rotation.

will try to get a more accurate idea of how long soon.

**Comment by cBournhonesque** [comment]
The `System 'bevy_ecs::event::event_update_system<.......>' has not run for 3258167296 ticks. Changes older than 3258167295 ticks will not be detected.` logs are expected; bevy's change detection doesn't work after more than ~15minutes.
However lightyear should recover seamlessly from this. It doesn't recover by itself?

**Comment by RJ** [comment]
ok yeah the "system has not run" thing is a red herring, it happened before i saw those messages this time. 

i restarted the server, connected a chrome wasm client, flew about smoothly, then unfocussed the chrome window for 15 mins.

when i came back, the normally buttery smooth movement looks like this:

https://github.com/cBournhonesque/lightyear/assets/29747/011aa985-cc3e-4f31-91e5-d9d2fc77674a

nothing logged on client or server to give a clue.

**Comment by RJ** [comment]
ah, this weird behaviour is the same if a leave a native client alone for 15m too..

**Comment by Nul-led** [comment]
Yep thats defo tick wrapping then, idk why the existing fix doesnt work tho

**Comment by RJ** [comment]
could you elaborate on what the tick wrapping issue is?

**Comment by cBournhonesque** [comment]
Either the bevy ticks (u32) or the lightyear ticks (u16) are wrapping around after a certain amount of time (around 15minutes for lightyear) which might be causing issues when comparing ticks.
To avoid this, I have:
- unit tests that check that tick wrapping is handled (but they are probably not comprehensive)
- a system that runs regularly and updates internal ticks to account for the wrapping

I refactored some of the replication code recently, maybe it broke some of the tick-wrapping specific logic.

The issue in your video is for the white ball's movement, right?

**Comment by RJ** [comment]
hard to pinpoint what is wrong in the video – the ball is janky, the player movement feels stuttery, the bullets appear to move backwards at some point.

**Comment by cBournhonesque** [comment]
Fixed this in https://github.com/cBournhonesque/lightyear/pull/497 (only in `cb/0.16` branch)

Some of the tick wrapping logic had indeed been broken with the replication refactor.
I added a stronger unit test so hopefully these kind of silent breakages won't resurface
