### ISSUE TITLE
Bincode instead?

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#489]
What's the reason for using bitcode instead of [bincode](https://github.com/bincode-org/bincode), which is arguably more mature and has wider adoption in production scenarios?

**Comment by msvbg** [comment]
https://github.com/cBournhonesque/lightyear/pull/452

**Comment by simbleau** [comment]
Gotcha, so this is a docs issue then. The README still specifies that bitcode is used.

**Comment by cBournhonesque** [comment]
The main reason was that bitcode is way more performant and efficient than bincode.
However it doesn't support serializing/deserializing directly from `impl Read` or `impl Write` so it was a bit tedious to maintain.
You're right the readme should be updated

**Comment by cBournhonesque** [comment]
Another benefit was that `bitcode` used bitpacking to reduce the bandwidth (a bool would only take 1 bit) vs 1 bool takes 1 byte in bincode

**Comment by Nul-led** [comment]
I suppose thats where the performance differences came from since bitpacking is pretty expensive.

**Comment by Nul-led** [comment]
Oh i misread, thought bincode was faster

**Comment by cBournhonesque** [comment]
I switched to bincode to be able to serialize/deserialize from an `impl Read` or `impl Write`
