### ISSUE TITLE
Where did `client_send_interval` and `server_send_interval` go?

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#510]
Between 0.15.1 and main, `client_send_interval` and `server_send_interval` disappeared in favor of a `server_replication_rate`.

I was able to fix this, and found it easily,

changing on the server:

```rust
replication: ReplicationConfig {
                send_interval: SERVER_REPLICATION_RATE,
                ..default()
            },
```
and on the client:
```rust
            replication: ReplicationConfig {
                send_interval: CLIENT_REPLICATION_RATE,
                ..default()
            },
```

But I'm suddenly having a familiar issue where the client becomes very bottlenecked and lags heavily because it can't keep up with inputs again.

Is there an input_send_rate that's missing? How can I ensure the client is sending at a rate of 100ms again?

**Comment by simbleau** [comment]
Just found https://github.com/cBournhonesque/lightyear/pull/466

**Comment by cBournhonesque** [comment]
The replication_rate can now be set per channel, as you found!

The `replication_interval` is separate and is set in the `ReplicationConfig`

**Comment by simbleau** [comment]
What about the input send rate? That's my issue here.

**Comment by cBournhonesque** [comment]
Are you sure the input send rate is making you lag; not the general simulation rate? (tick_interval)
I'm a bit surprised that sending the input messages (which are pretty small) frequently causes issues.

I don't think there was a way to adjust the `InputChannel` send rate; I added an option here: https://github.com/cBournhonesque/lightyear/blob/main/lightyear/src/client/input/native.rs#L76

**Comment by simbleau** [comment]
> Are you sure the input send rate is making you lag; not the general simulation rate? (tick_interval) I'm a bit surprised that sending the input messages (which are pretty small) frequently causes issues.
> 
> I don't think there was a way to adjust the `InputChannel` send rate; I added an option here: https://github.com/cBournhonesque/lightyear/blob/main/lightyear/src/client/input/native.rs#L76

Fixed when I set the input_send_rate to something lower than the frame rate.

Thanks for the assist!
