### ISSUE TITLE
Add ActionState on server entity if we receive an InputMessage for it

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#522]
In the examples, the ActionState is replicated from the PrePredicted entity to the server, so there's no need to add ActionState.

But when there is no PrePrediction, we need to add ActionState on the server entity manually. Maybe we should instead add it in lightyear whenever we receive an InputMessage for an entity? (it can be confusing to users to figure out that they have to add the ActionState themselves)

**Comment by Nul-led** [comment]
This sounds useful
