### ISSUE TITLE
Support replicate component as resource

### ISSUE THREAD

**Issue by notmd** [cBournhonesque/lightyear#541]
Example with `Health` component. On server there will many players each have one `Health` component, but on the client there is only one `Health` component, having to query it each is really verbose, accessing it directly with `Res<Health>` is more ergonomic. 
Block on https://github.com/cBournhonesque/lightyear/issues/540 otherwise multiple components replication will override the resource

**Comment by cBournhonesque** [comment]
I'm not sure I understand how this would work.
You mean that the component is authoritative on the server and lives on an entity, but when it's replicated it gets replicated on a resource?

I think that's probably an anti-pattern, you would need `Health` to be both a component and a resource, you would need different ways of handling it for client/server code. I think this kind of pattern is not very bevy-like; I would suggest to simply create an entity on the client as well. (what if you want to add co-op and have 2 player entities on the client? or bots?)

**Comment by notmd** [comment]
I agree this kind of pattern is anty-pattern. I think I can create a system to sync the replicated component with the resource for my use case instead.
