### ISSUE TITLE
Don't send input if <condition>

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#610]
My game has chat. If the user starts typing, I want to ignore inputs.

They may send a message that uses the keys WASD - Which are used for movement.

However I can't find a way to tell Lightyear not to send the input if `state.typing` is true.

What should I do?

**Comment by cBournhonesque** [comment]
With the leafwing input it is possible to disable leafwing ActionStates and systems.
There is an open issue to also stop replicating inputs from client->server if the inputs are disabled on the client.

For your specific use-case, you could use run-conditions or states to at least no send inputs on the client while the chat window is open (lightyear would still send inputs to the server, but those inputs would be empty)

**Comment by simbleau** [comment]
Good idea!

**Comment by cBournhonesque** [comment]
I meant that you can make sure to call `ActionState.disable()` while the chat window is open, which means that the ActionState will be empty. It will still be replicated to the server but the state will be small
