### ISSUE TITLE
Predicted entities don't sync hierarchy

### ISSUE THREAD

**Issue by nick-e** [cBournhonesque/lightyear#627]
Predicted entities on clients do not sync their hierarchies with their confirmed counterparts after the `ReplicateHierarchy { recursive: true }` component is inserted into the parent entity on the server. The predicted entities exist but the predicted parent entities have no children and the predicted children have no parent. Meanwhile, the confirmed parent entities and confirmed child entities have their hierarchy correctly synced and the children have the `ParentSync` component. I expect that the predicted entities would sync their hierarchy with their confirmed counterparts.

**Comment by cBournhonesque** [comment]
Thanks for the report. I guess the `replication_groups` doesn't trigger this because it uses a custom `PlayerParent` component instead of going through the `ParentSync` machinery

**Comment by nick-e** [comment]
Closing because this is a duplicate of https://github.com/cBournhonesque/lightyear/issues/545
