### ISSUE TITLE
Disallow common `f32` functions in favor of the `bevy_math` crate

### ISSUE THREAD

**Issue by nick-e** [cBournhonesque/lightyear#648]
I noticed that the `bevy_math` crate disallows using common `f32` functions and recommends replacing them with functions defined in the `bevy_math` crate: https://github.com/bevyengine/bevy/blob/main/crates/bevy_math/clippy.toml. The file states that the replacement functions are deterministic. I see that lightyear uses a few of these common `f32` functions and I'm wondering if lightyear should also disallow them and use `bevy_math` instead. `bevy` just recently did that: https://github.com/bevyengine/bevy/pull/15239.

**Comment by nick-e** [comment]
Never mind, it looks like the `f32` functions are used in scenarios where determinism isn't a problem like visual interpolation.

**Comment by cBournhonesque** [comment]
It might still be worth doing for good practice, thanks for bringing this up!
