### ISSUE TITLE
Missing TripleAxis from ActionKind in the leafwing input manager integration.

### ISSUE THREAD

**Issue by Lommix** [cBournhonesque/lightyear#679]
On the main branch in the spaceship example there is missing inputKind in the Leafiwing Integration.

The Example fails to compile with the following error:

```rust
error[E0599]: no variant or associated item named `TripleAxis` found for enum `ActionKindData` in the current scope
   --> lightyear/src/inputs/leafwing/action_diff.rs:103:37
```

**Comment by msvbg** [comment]
Did you run `cargo update`? This is in the latest version of LWIM

**Comment by Lommix** [comment]
My bad. Fixed after update
