### ISSUE TITLE
chrono pinned

### ISSUE THREAD

**Issue by simbleau** [cBournhonesque/lightyear#681]
https://github.com/cBournhonesque/lightyear/blob/4425f91c69377ef0ef8de955e9fae4d075123d46/lightyear/Cargo.toml#L52

Why is chrono pinned to 0.4.34?

It is causing me an issue, can we remove this pin?

**Comment by cBournhonesque** [comment]
Unfortunately chrono 0.4.35 deprecated some TimeDelta constructors that are used in lightyear: https://github.com/chronotope/chrono/pull/1450

I see that the change was reverted in subsequent versions; so it should be possible to use the latest version of chrono
https://github.com/chronotope/chrono/pull/1543
