### ISSUE TITLE
WASM Examples wont run in browser

### ISSUE THREAD

**Issue by TheGreenPlanet** [cBournhonesque/lightyear#684]
### Summary

I've encountered an issue while trying to run any example specifically for WASM (e.g., `simple_box`, `interest_management`) using `trunk serve`. I’ve tested both the `main` branch and the latest tagged version (`0.17.0`). While the examples compile successfully to WebAssembly, they display a blank white page when opened in either Firefox or Chrome.

### Steps to Reproduce

1. Clone the repository and checkout either the `main` branch or the `0.17.0` tag.
2. Run `trunk serve` to build and serve any example, such as `simple_box` or `interest_management`.
3. Open the served page (default: `http://127.0.0.1:8080`) in a browser.

### Expected Behavior

The example should load and display the expected content.

### Actual Behavior
(Using the ```interest_manegement``` example)

A blank white page appears in both Firefox and Chrome. Opening the browser console shows the following error:
```Uncaught TypeError: The specifier “env” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.```
Error originates from:
```interest_management-b07c367cc454b4e.js:1:30 (http://127.0.0.1:8080/interest_management-b07c367cc454b4e.js)```
The highlighted line in the code is:

```javascript
import * as __wbg_star0 from 'env';
```

### Analysis
This error seems to occur because WebAssembly is attempting to import an "env" symbol that doesn't exist, possibly due to a missing or incorrectly configured crate dependency.

### Debugging Attempts
Following the suggestions in [this discussion](https://github.com/rustwasm/wasm-bindgen/discussions/3500#discussioncomment-6334669), I attempted to inspect the .wasm file using wasm2wat to identify the missing symbol/crate. However, running wasm2wat on the file failed, showing this message:
```Error: Aborted(). Build with -s ASSERTIONS=1 for more info.```
I tried building with additional flags as suggested:
```bash
RUSTFLAGS="--cfg=web_sys_unstable_apis -C debuginfo=2" trunk serve
```
This did not resolve the issue.

### Environment
 * Browser: Firefox and Chrome (latest versions)
 * OS: Ubuntu 24.04
 * Trunk Version: trunk 0.21.4
 * Rust Version: 1.82.0

Any guidance on resolving this would be greatly appreciated (Though I got a feeling that this might be a "Me issue").

**Comment by cdata** [comment]
Ooo, I just hit this today. I have not fixed it yet, but here is the progress of my investigation so far:

I used `wasm-tools` to look for what was bringing in `env`, and I _think_ the culprit is `ring`:

```sh
❯ wasm-tools print ../../target/wasm32-unknown-unknown/debug/wasabi-16.wasm | grep \"env\"
  (import "env" "ring_core_0_17_8_bn_from_montgomery_in_place" (func $ring_core_0_17_8_bn_from_montgomery_in_place (;3;) (type 31)))
  (import "env" "ring_core_0_17_8_limbs_mul_add_limb" (func $ring_core_0_17_8_limbs_mul_add_limb (;4;) (type 26)))
  ```

I tried forcing the `wasm32_unknown_unknown_js` feature on for `ring` but that doesn't seem to fix the issue. But, this could be a starting point for more investigation.

**Comment by cdata** [comment]
Okay, have some time to do additional investigation....

- Confirmed that this problem occurs on at least one `lightyear` example (`avian_physics`) when using `trunk serve`
- It seems like the _only_ thing that `ring` is used for is [one really small utility function that is intended for tests](https://github.com/cBournhonesque/lightyear/blob/7d714079a540f3d0233a084de5a0603c7fc5caa9/lightyear/src/transport/webtransport/client_wasm.rs#L53)
- Inlining the required utility function and removing the `ring` dependency resolves this problem

**Comment by cdata** [comment]
I put up a PR with a "fix" of sorts. But, there may be better options.

**Comment by cdata** [comment]
Recording a related tip [from Discord](https://discord.com/channels/691052431525675048/1189344685546811564/1304737928601141308) here for posterity:

> i've run into the "ring breaks wasm builds" issue a couple of times, trying to remember how i solved it. i've also run into a gnarly silent linker failure that only causes issues at runtime (a js issue), which is fixed by using clang instead of gnu cc, at least on my machines.   i build wasm with these flags:
> ```
> TARGET_CC=/usr/bin/clang RUSTFLAGS=--cfg=web_sys_unstable_apis CARGO_BUILD_TARGET=wasm32-unknown-unknown cargo build etc..
> ```
> i skimmed your pr to remove ring, and that seems helpful.

**Comment by RJ** [comment]
> Recording a related tip [from Discord](https://discord.com/channels/691052431525675048/1189344685546811564/1304737928601141308) here for posterity:
> 
> > i've run into the "ring breaks wasm builds" issue a couple of times, trying to remember how i solved it. i've also run into a gnarly silent linker failure that only causes issues at runtime (a js issue), which is fixed by using clang instead of gnu cc, at least on my machines.   i build wasm with these flags:
> > ```
> > TARGET_CC=/usr/bin/clang RUSTFLAGS=--cfg=web_sys_unstable_apis CARGO_BUILD_TARGET=wasm32-unknown-unknown cargo build etc..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i skimmed your pr to remove ring, and that seems helpful.

yep, this fixed this exact issue for me:

```
# Use LLVM clang not default cc, otherwise prone to weird silent wasm linker failures.
# Browser reports: 
#    Uncaught TypeError: Failed to resolve module specifier "env".
#    Relative references must start with either "/", "./", or "../".
#
# and .js file starts with:
#   import * as __wbg_star0 from 'env';
#
# Using clang prevents this.
ENV TARGET_CC=/usr/bin/clang
```
