### ISSUE TITLE
Refactor 3d sample, so it is more linear with common server authoritative logic

### ISSUE THREAD

**Issue by Sirmadeira** [cBournhonesque/lightyear#685]
This may not make a lot of sense but in my opinion, predicted entities should always first be spawned in client and them aligned with server information. 
In avian_3d sample doesntt do that. Also the sample seens to be extremely buggy.Add gravity and boom he breaks, constant collision and boom he breaks.
Also he seens to want to correct component even when stationary and almost perfectly aligned with server

A lot of things are not very lightyear like, in my opinion, for example we dont utilize the pre predicted flag. 
Predict all is literally a dead flag.
I can refactor it and make it more newbee friendly, perhaps even avoid the usage of visual interpolation set.

**Comment by cBournhonesque** [comment]
I think in most cases, running in prediction on the client **after** receiving the replicated entity is simpler to understand. Pre-prediction is (in my mind) a bit niche.

I think you make good points about other parts of the example being broken, though

**Comment by Sirmadeira** [comment]
You know I think. I am gonna avoid the whole when added predicted functions occur. I think it makes way more sense to follow the prepredicted workflow.

**Comment by Sirmadeira** [comment]
@cBournhonesque Well there was an extreme issue with stale inputs. I just nabbed the solution from RJ. And it improved a lot. But there is still an issue with constant collision and gravity. Still investigating what it is keep you patched up
