### ISSUE TITLE
TODO - https://docs.rs/lightyear/latest/src/lightyear/client/networking.rs.html#471

### ISSUE THREAD

**Issue by Sirmadeira** [cBournhonesque/lightyear#727]
* I shall try to implement this little features, as it would be pretty neat and necessary for any editor or egui based app
* As otherwise it requires user to send, an event to run connect client if he wants to control it. Which is just meh,

Here are my steps:

1.  Make client world, have an extra impl that makes it possible to run connect client. 
2.  Change logics based on world, itself so it takes into consideration our derived version of it. 
Warning: This might have additionals

**Comment by cBournhonesque** [comment]
The current logic is that the client runs `Commands.connect_client()`; the command gets executed later and simply switches the state to Connecting.
On the state change, the actual connecting logic starts. But the error is not caught.

We could emit a 'ConnectionError' event with the error information that the client could catch. Maybe it's actually better if the connection process takes a while, to not block the thread?
