### ISSUE TITLE
simple_box example stops working after 9 minutes

### ISSUE THREAD

**Issue by healingdrawing** [cBournhonesque/lightyear#77]
server/client interaction stops  working  properly after next step.

use lightyear example **simple_box**

- run server
- run client
- do some moves periodically (or client will closed with panic)
```
thread 'Compute Task Pool (1)' panicked at /home/user/git/lightyear/lightyear/src/inputs/native/input_buffer.rs:98:18:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `lightyear::client::input::write_input_event<simple_box::protocol::myprotocol_module::MyProtocol>`!
Encountered a panic in system `bevy_time::fixed::run_fixed_update_schedule`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
- after nine minutes +- fail happens . always, after that looks like confirmed position does not updated on client side properly

[2024-01-13 20-31-46.webm](https://github.com/cBournhonesque/lightyear/assets/39751647/fd5fe938-dc97-4c6f-9b63-271a2986810f)

**Comment by cBournhonesque** [comment]
Fixed with https://github.com/cBournhonesque/lightyear/pull/80
