### ISSUE TITLE
Handle entity owners natively in lightyear

### ISSUE THREAD

**Issue by cBournhonesque** [cBournhonesque/lightyear#95]
Currently the examples have an ugly "Global" resource that helps you track who is the owner of an entity.

I'm not entirely sure that's needed, because the `PlayerId` component should contain the client-id currently.

But in any case it might be better if lightyear adds a component/resource called Owner that helps track natively which client owns which entity.

**Comment by Nul-led** [comment]
Maybe this can be integrated with rooms?

**Comment by cBournhonesque** [comment]
Yes, maybe lightyear could spawn one room per connected player

**Comment by cBournhonesque** [comment]
Added a `GlobalMetadata` resource on both the client and server which will contain metadata about the connection.
Currently it only contains the `client_id`.

**Comment by cBournhonesque** [comment]
I removed the GlobalMetadata resource as it was confusing; I think we should look at what other libraries (unity, unreal) do for this

**Comment by cBournhonesque** [comment]
There would be a distinction between:

1) Who is simulating the entity and sending replication updates?
(in most cases it is the server, but in some client-to-server replication cases it could be a client. It's not enough to check who has the `Replicate` component, because the server will also have the `Replicate` component to propagate the updates to other clients)
A client could be sending replication updates even for entities that they are not controlling/moving.

2) Who is controlling the entity?
This is basically: which peer is controlling/moving a given entity? Usually it's the client who added the `InputLeafwing` component on an entity. However the client adds the `InputLeafwing` on the `Predicted` entity, it could be useful to know on the server-side (i.e. Confirmed entity) who is the controller for a given entity.
(Then, if the controller disconnects, that entity could also get despawned?)

3) Who has authority?

Who is acting as server for the simulation? usually it's the actual server, but if we're running in HostServer mode it's one of the clients acting as server?
This concept is still not clear to me.

_______

I feel like 1) and 2) could be useful if they were handled in lightyear.
1) could be useful to handle transfering the 'replication ownership' of an entity
2) could be useful for the server to keep track of who is the ClientId controlling an entity

**Comment by Nul-led** [comment]
@cBournhonesque can this be closed then?

**Comment by cBournhonesque** [comment]
I think this can be closed.

We have the 'Controlled' component which tracks which client logically 'controls' a given entity. This doesn't mean that the client is sending replication updates for this entity, it just means that the client is the 'owner' of that entity. When the client disconnects, the server can automatically despawn their controlled entities. The server maintains a `ControlledEntities` component for each client to keep track of their controlled entities.

And now (https://github.com/cBournhonesque/lightyear/pull/594) we have the concept of 'authority': which peer is actively simulating and sending replication updates for a given entity. An entity can have at most one authoritative peer.

So you could have:
- server authority with client inputs. The classic case where the client sends inputs about an entity, the server applies the inputs and sends back updates to the client
- server authority without client inputs: an entity that is simulated by the server and replicated to clients (for example a NPC)
- client authority: the client simulates the entity and sends updates to the server (who can rebroadcast the updates to other clients)
